### ISSUE TITLE
Garmin breaks Garpy? now always getting a HTTP: 402 

### ISSUE THREAD

**Issue by jamesmstone** [felipeam86/garpy#34]
Hello,

 firstly, thanks for a super useful tool.  
This was working well for me up until ~ 1 week ago https://github.com/jamesmstone/garmin/actions?page=3

I am now however getting the following error: when running:

```
garpy run garpy download --username *** --password '***' data/garmin
```

```
2022-12-21 08:15:29 INFO - Authenticating GarminClient(username='***', user_agent='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.101 Safari/537.36')
2022-12-21 08:15:36 INFO - Claiming auth ticket
2022-12-21 08:15:47 INFO - Downloading the following formats: ('summary', 'mkl', 'original', 'details', 'tcx', 'gpx') to this folder: /data/garmin
2022-12-21 08:15:47 INFO - Querying list of activities
2022-12-21 08:15:48 ERROR - Failed to fetch activities 0 to 99.
Response code: 402

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/root/.cache/pypoetry/virtualenvs/garpy-il7asoJj-py3.10/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/garpy-il7asoJj-py3.10/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/root/.cache/pypoetry/virtualenvs/garpy-il7asoJj-py3.10/lib/python3.10/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.cache/pypoetry/virtualenvs/garpy-il7asoJj-py3.10/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.cache/pypoetry/virtualenvs/garpy-il7asoJj-py3.10/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/garpy/cli.py", line 113, in download
    downloader(formats=formats, activity_id=activity_id)
  File "/garpy/download.py", line 134, in __call__
    activities = Activities.list(self.client)
  File "/garpy/activity.py", line 159, in list
    for activity in client.list_activities()
  File "/garpy/client.py", line 229, in list_activities
    response = self.get(
  File "/garpy/client.py", line 192, in get
    raise ConnectionError(err_message)
ConnectionError: Failed to fetch activities 0 to 99.
Response code: 402

```

Please let me know if I can provide any more detailed information.

**Comment by felipeam86** [comment]
Hi @jamesmstone

Super cool how you are using garpy! I will take a look at it and try to replicate the automation with github actions + datasette.

Thanks for opening this issue. I have fixed it and published a new version. Can you please upgrade and let me know if this fixes the issue in your end? Latest version is now 0.3.7

All credits go to https://github.com/petergardfjall/garminexport/pull/92

**Comment by jamesmstone** [comment]
💪 I will give it a go later today. Thanks

________________________________

**Comment by jamesmstone** [comment]
Thanks that works! 
You are a champion. If you are ever in Melbourne Australia I will have to buy you a beer🍺

**Comment by felipeam86** [comment]
Thanks @jamesmstone

If you ever come to medellín, Colombia, I'll buy you a beer!
